name: Download y2b video and upload to aliyundrive

on:
  workflow_dispatch:
    inputs:
      url:
        description: "youtube视频地址："
        required: true
      res:
        description: "分辨率偏好："
        required: true
        default: "1080p"
        type: choice
        options:
          - 1080p
          - 720p
          - 480p
          - 360p
      drive_dir:
        description: "文件上传的网盘目录："
        required: true

env:
  TOOLS_PATH: /usr/local/bin/tools
  MAIN_REPO: main
  PRIVATE_REPO: private-scripts
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ${{ env.MAIN_REPO }}

      - name: Checkout private scripts
        uses: actions/checkout@v3
        with:
          repository: nomeqc/private-scripts
          token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
          path: ${{ env.PRIVATE_REPO }}


      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: pip cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles(format('{0}/requirements.txt', env.MAIN_REPO)) }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: tools cache
        id: tools-cache
        uses: actions/cache@v3
        with:
          path: ${{ env.TOOLS_PATH }}
          key: ${{ runner.os }}-tools-${{ hashFiles(format('{0}/scripts/install.sh', env.MAIN_REPO)) }}
          restore-keys: |
            ${{ runner.os }}-tools-

      - name: Install dependency
        run: |
          bash ${MAIN_REPO}/scripts/install.sh
        env:
          TOOLS_CACHE_HIT: ${{ steps.tools-cache.outputs.cache-hit }}
      
      - name: Run
        run: |
          cp -f ${PRIVATE_REPO}/xmly2aliyundrive/aliyundrive_client.py ${MAIN_REPO}/scripts/aliyundrive_client.py
          cp -f ${PRIVATE_REPO}/util/dingtalk.py ${MAIN_REPO}/scripts/dingtalk.py
          python ${MAIN_REPO}/scripts/run.py "${URL}" "${RES}" "${DRIVE_DIR}"
        env:
          URL: ${{ github.event.inputs.url }}
          RES: ${{ github.event.inputs.res }}
          DRIVE_DIR: ${{ github.event.inputs.drive_dir }}
